version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ../frontends/app
      dockerfile: Dockerfile
      target: dev
    environment:
      BACKEND_URL: ${BACKEND_URL}
    ports:
      - '3000:3000'
    volumes:
      - ../frontends/app:/app
      - /app/node_modules
      - /app/.next

  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DATABSE_PASSWORD}
    ports:
      - '1433:1433'
